package h7;

import e6.q;

/* JADX INFO: loaded from: classes2.dex */
public interface a<T> {

    /* JADX INFO: renamed from: h7.a$a, reason: collision with other inner class name */
    public static final class C0120a {
        public static <T> T[] a(a<T> aVar, int i8) {
            throw new q("Generated by Android Extensions automatically");
        }
    }
}
